const filter = {
    "홍비" : "HongBi",
    "홍시" : "Hongsi",
    "루이" : "Louis",
    "미미" : "Mimi",
    "에드" : "Ed",
    "쿠키엄마" : "Cookie Mom",
    "아빠" : "Dad",
    "엄마" : "Mom",
    "할아버지" : "Grandfather",
    "할머니" : "Grandma",
    "쿠키" : "Cookie",
    "쿠크삼촌" : "Uncle Kookeu",
    "모리인형" : "Mori",
    "울리" : "Woolly",
    "코끼리아저씨" : "Mr.Elephant",
    "올빼미할아버지" : "Mr.Owl",
    "양아줌마" : "Mrs.Sheep",
    "부우" : "Boo",
    "엘리선생님" : "Teacher Elly",
    "외할머니" : "Maternal grandmother",
    "리아" : "Lia",
    "빙빙" : "BingBing",
    "아밍" : "AhMing",
    "칭칭" : "ChingChing",
    "아이링여왕" : "Queen I-ring",
    "달통" : "Daltong",
    "박시" : "Boxy",
    "레드" : "Red",
    "옐로우" : "Yellow",
    "핑크" : "Pink",
    "브라운" : "Brown",
    "블랙" : "Black",
    "마룬" : "Maroon",
    "프러시안" : "Prussian",
    "그레이" : "Gray",
    "아이보리" : "Ivory",
    "행복" : "Happiness",
    "중립" : "Neutral",
    "슬픔" : "Sadness",
    "놀라움" : "Surprise",
    "두려움" : "Fear",
    "분노" : "Anger",
    "혐오" : "Disgust",
    "여름" : "Summer",
    "유니" : "Yuni",
    "토토" : "Toto",
    "권두언" : "Kwon Doo-eon",
    "고아라" : "Go A-ra",
    "기민철" : "Ki Min-cheol",
    "선종선" : "Sun Jong-sun",
    "수진" : "Su-jin",
    "나대우" : "Na Dae-woo",
    "윤지석" : "Yoon Ji-seok",
    "지근욱" : "Ji Geun-wook",
    "이대로" : "Lee Dae-ro",
    "렉스" : "Rex",
    "파브로" : "Fabro",
    "에밀리" : "Emily",
    "존" : "John",
    "빌" : "Bill",
    "카야" : "Kaya",
    "아칸" : "AkanWei",
    "라키나" : "Rakina",
    "레오" : "Reo",
};